name: code
description: "Gaming App to simulate future Arduino connexion and behavior."

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  #flutter_blue: ^0.8.0
  #flutter_bluetooth_serial: ^0.4.0
  all_bluetooth: ^0.1.0
  flutter_blue_plus: ^1.4.0
  get: ^4.6.5
  provider: ^6.1.2
  #bluetooth_classic: ^0.0.1
  #flutter_bluetooth_basic: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logoTPV5.png
    - assets/panier.png
    - assets/panier.gif
    - assets/ballon.png
    - assets/Rack_empty.png
    - assets/Rack_1Ball.png
    - assets/Rack_2Balls.png
    - assets/Rack_3Balls.png
    - assets/terrain.png
    - assets/sprite_point_bonus4.png
    - assets/sprite_point_bonus3.png
    - assets/sprite_point_bonus2.png
    - assets/sprite_precision_bonus1.png
    - assets/sprite_precision_bonus2.png
    - assets/sprite_precision_bonus3.png
    - assets/sprite_precision_bonus4.png
    - assets/sprite_precision_bonus5.png
    - assets/sprite_precision_bonus6.png
    - assets/sprite_precision_bonus7.png
    - assets/sprite_precision_bonus8.png
    - assets/sprite_precision_bonus9.png
    - assets/sprite_precision_bonus10.png
    - assets/Seconde_Chance_Bonus.png
    - assets/count_before_bonus0.png
    - assets/count_before_bonus1.png
    - assets/count_before_bonus2.png
    - assets/count_before_bonus3.png

